### PR TITLE
Lost in thoughts all alone

### PR DESCRIPTION
**Pull request by MercifulCode**
Currently working on upgrading parts of the codebase with the end goal of adding in a tab for a U-Map visualization.

Breaking the modernization into chunks, this first PR has no functionality changes as it just introduces a simple package.json with the code run through prettier to establish a baseline format.

cc @npgauth

### CODE REVIEW

**Comment by MercifulCode** [comment]
Do you have write access to merge this in, @sacdallago ?

Tagging @rocreguant just in case!

**Comment by sacdallago** [comment]
I do -- should I? Who is @npgauth? :D :D

**Comment by MercifulCode** [comment]
If you wouldn't mind! ;)

@npgauth is Nick !

**Comment by sacdallago** [comment]
Hi Nick @npgauth I see the gauth now, makes sense :)
Merged by the power of Greyskull

**Comment by MercifulCode** [comment]
Thank you!

https://31.media.tumblr.com/tumblr_m9jmrvGatD1qlvd4eo1_250.gif

**Pull request merged**
