### PR TITLE
Running code through prettier

### PR DESCRIPTION
**Pull request by MercifulCode**
Currently working on upgrading parts of the codebase with the end goal of adding in a tab for a U-Map visualization.

Breaking the modernization into chunks, this first PR has no functionality changes as it just introduces a simple package.json with the code run through [prettier](https://prettier.io/) to establish a baseline format.

cc @npgauth

### CODE REVIEW

**Comment by sacdallago** [comment]
Please, don't merge this in master. Let's make a `development` branch and merge in there. Master is live at https://alignmentviewer.org && used by evcouplings

**Comment by sacdallago** [comment]
(not claiming this PR is bad, I think it's brilliant. It's just that it's a bit too many changes to smoothly test out, esp. since we don't have automated tests. Also `currently` is bad for production, even if production just relies on the built. Better just to merge in master when the changes are cosmetic, functional and complete)

**Comment by npgauth** [comment]
We will definitely run all changes by you before any merging! This is all
in preparation to add a UMAP sequence space viewer as an extra tab :-)

Probably worth a discussion with you before we starting adding though —
what is your availability looking like early next week?



On July 5, 2019 at 08:39:38, Christian Dallago (notifications@github.com)
wrote:

(not claiming this PR is bad, I think it's brilliant. It's just that it's a
bit too many changes to smoothly test out, esp. since we don't have
automated tests. Also currently is bad for production, even if production
just relies on the built. Better just to merge in master when the changes
are cosmetic, functional and complete)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dfci/alignmentviewer/pull/36?email_source=notifications&email_token=AAXIXXVQWO6C2NKSXH7EVPDP546IVA5CNFSM4H5MGXKKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZJNPPA#issuecomment-508745660>,
or mute the thread

**Comment by MercifulCode** [comment]
Ah, for sure - thanks @sacdallago !

**Comment by sacdallago** [comment]
This isn't my work. I'm just maintaining this as part of evcouplings :) @rocreguant is probably better suited for high level decisions. I'm happy to talk though -- I was long thinking about making this a bit more... modular, reorganize. Just didn't get to it when there.

Mail me some possible meeting times your morning time? That's my afternoon ;)

**Pull request closed without merging**
